name: Quarterly Release

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Create and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Determine Version Tag
        id: version
        run: |
          echo "tag=v$(date +'%Y.%m')" >> "$GITHUB_OUTPUT"

      - name: Create Git Tag and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG
        env:
          TAG: ${{ steps.version.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Typst
        uses: typst-community/setup-typst@v4.0.3

      - name: Build the Artifact
        run: typst compile main.typ resume.pdf

      - name: Create GitHub Release using CLI
        run: |
          gh release create $TAG resume.pdf --title "$TAG" --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.version.outputs.tag }}
